spring:
  application:
    name: orchestrator-service

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

services:
  client:
    name: client-service
  catalog:
    name: catalog-service
  order:
    name: order-service

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://service-registry:8762/eureka

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
