spring:
  application:
    name: orchestrator-service
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

    listener:
      simple:
        default-requeue-rejected: false

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://service-registry:8762/eureka

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
