server:
  port: 0
  error:
    include-stacktrace: never
    include-message: always

spring:
  application:
    name: catalog-service
  mvc:
    problemdetails:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/tech-challenge

  datasource:
    url: jdbc:postgresql://catalog-service-db:5432/catalog-service-db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator

# Eurika configuration
eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://service-registry:8762/eureka

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
