spring:
  application:
    name: service-registry

server:
  port: 8762

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://service-registry:8762/eureka/

logging:
  level:
    br.com.fiap.serviceregistry: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{correlationId:-}] [%thread] %-5level %logger{36} - %msg%n"
