name: tech-challenge-fase-03

services:

  keycloak:
    #image: quay.io/keycloak/keycloak:26.5.4
    build:
      context: ./docker
      dockerfile: ./keycloak/Dockerfile.keycloak
    command: start-dev --import-realm --http-port=8080
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://keycloak-db:5432/keycloak
      - KC_DB_USERNAME=root
      - KC_DB_PASSWORD=root
      - KC_IMPORT_REALM=realm-export.json
    volumes:
      - ./docker/keycloak/realm:/opt/keycloak/data/import
    depends_on:
      keycloak-db:
        condition: service_healthy
    networks:
      - fase3net
  
  keycloak-db:
    image: postgres:15
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - fase3net

  auth-service-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth-service-db
    volumes:
      - auth-service-db_data:/var/lib/postgresql/data
    networks:
      - fase3net

  client-service-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: client-service-db
    volumes:
      - client-service-db_data:/var/lib/postgresql/data
    networks:
      - fase3net

  catalog-service-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: catalog-service-db
    volumes:
      - catalog-service-db_data:/var/lib/postgresql/data
    networks:
      - fase3net

  order-service-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: order-service-db
    volumes:
      - order-service-db_data:/var/lib/postgresql/data
    networks:
      - fase3net

  payment-service-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: payment-service-db
    volumes:
      - payment-service-db_data:/var/lib/postgresql/data
    networks:
      - fase3net

  restaurant-service-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: restaurant-service-db
    volumes:
      - restaurant-service-db_data:/var/lib/postgresql/data
    networks:
      - fase3net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # AMQP
      - "15672:15672"  # Management UI
    volumes:
      - ./docker/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
    environment:
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: >
        -rabbitmq_management load_definitions "/etc/rabbitmq/definitions.json"
    networks:
      - fase3net

  procpag:
    # image: docker.io/erickemprobr/procpag:latest
    # https://github.com/proferickmuller/go-procpag
    # image: go-procpag
    image: docker.io/erickemprobr/procpag:latest
    platform: linux/amd64
    ports:
    - "8089:8089"
    networks:
    - fase3net

  service-registry:
    build:
      context: .
      dockerfile: ./service-registry/Dockerfile
    ports:
      - "8762:8762"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8762/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - fase3net

  api-gateway:
    build:
      context: .
      dockerfile: ./api-gateway/Dockerfile
    ports:
      - "8761:8761"
    networks:
      - fase3net
    depends_on:
      service-registry:
        condition: service_healthy

  auth-service:
    build:
      context: .
      dockerfile: ./auth-service/Dockerfile
    networks:
      - fase3net
    depends_on:
      auth-service-db:
        condition: service_started
      service-registry:
        condition: service_healthy

  client-service:
    build:
      context: .
      dockerfile: ./client-service/Dockerfile
    networks:
      - fase3net
    depends_on:
      client-service-db:
        condition: service_started
      service-registry:
        condition: service_healthy

  catalog-service:
    build:
      context: .
      dockerfile: ./catalog-service/Dockerfile
    networks:
      - fase3net
    depends_on:
      catalog-service-db:
        condition: service_started
      service-registry:
        condition: service_healthy

  order-service:
    build:
      context: .
      dockerfile: ./order-service/Dockerfile
    networks:
      - fase3net
    depends_on:
      order-service-db:
        condition: service_started
      service-registry:
        condition: service_healthy
      rabbitmq:
        condition: service_started

  payment-service:
    build:
      context: .
      dockerfile: ./payment-service/Dockerfile
    networks:
      - fase3net
    depends_on:
      payment-service-db:
        condition: service_started
      service-registry:
        condition: service_healthy
      rabbitmq:
        condition: service_started

  restaurant-service:
    build:
      context: .
      dockerfile: ./restaurant-service/Dockerfile
    networks:
      - fase3net
    depends_on:
      restaurant-service-db:
        condition: service_started
      service-registry:
        condition: service_healthy
      rabbitmq:
        condition: service_started

  orchestrator-service:
    build:
      context: .
      dockerfile: ./orchestrator-service/Dockerfile
    networks:
      - fase3net
    depends_on:
      service-registry:
        condition: service_healthy
      rabbitmq:
        condition: service_started

networks:
  fase3net:

volumes:
  auth-service-db_data:
  client-service-db_data:
  catalog-service-db_data:
  order-service-db_data:
  payment-service-db_data:
  restaurant-service-db_data:
  keycloak_db_data:
