spring:
  application:
    name: api-gateway
  mvc:
    problemdetails:
      enabled: true
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: 6379
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth-service/**
          filters:
            - StripPrefix=1
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order-service/**
          filters:
            - StripPrefix=1
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment-service/**
          filters:
            - StripPrefix=1
        - id: restaurant-service
          uri: lb://RESTAURANT-SERVICE
          predicates:
            - Path=/restaurant-service/**
          filters:
            - StripPrefix=1
        - id: client-service
          uri: lb://CLIENT-SERVICE
          predicates:
            - Path=/client-service/**
          filters:
            - StripPrefix=1
        - id: catalog-service
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/catalog-service/**
          filters:
            - StripPrefix=1
        - id: orchestrator-service
          uri: lb://ORCHESTRATOR-SERVICE
          predicates:
            - Path=/orchestrator-service/**
          filters:
            - StripPrefix=1
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/tech-challenge

server:
  port: 8761
  error:
    include-stacktrace: never
    include-message: always

logging:
  level:
    root: INFO

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://service-registry:8762/eureka

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

