@startuml
title Tech Challenge Fase 03 - Sequência de Autenticação e Acesso JWT

actor Cliente
participant "API Gateway\n:8761" as APIGW
participant "Service Registry\nEureka :8762" as EUREKA
participant "Auth Service" as AUTH
database "Auth DB\nPostgres" as AUTHDB
participant "Keycloak\n:8000" as KC
database "Keycloak DB" as KCDB
participant "Order Service" as ORDER

== Descoberta de serviço ==
APIGW -> EUREKA: resolve auth-service

== Endpoint aberto (login) ==
Cliente -> APIGW: POST /auth/login
APIGW -> AUTH: encaminha credenciais
AUTH -> AUTHDB: consulta/atualiza contexto local (opcional)
AUTH -> KC: autentica usuário
KC -> KCDB: consulta realm/usuário
KCDB --> KC: dados de autenticação
KC --> AUTH: JWT / erro
AUTH --> APIGW: resposta de autenticação
APIGW --> Cliente: token JWT

== Endpoint protegido ==
Cliente -> APIGW: POST /orders (Bearer JWT)
APIGW -> APIGW: valida assinatura/expiração/perfil
APIGW -> EUREKA: resolve order-service
APIGW -> ORDER: encaminha com identidade do cliente
ORDER --> APIGW: resposta da operação
APIGW --> Cliente: resposta autorizada

@enduml
