spring:
  application:
    name: restaurant-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/tech-challenge
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        default-requeue-rejected: false

  datasource:
    url: jdbc:postgresql://restaurant-service-db:5432/restaurant-service-db
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: validate


app:
  rabbit:
    exchange: ex.main
    queues:
      in:
        orquestradorRestaurantes: Orquestrador-Restaurantes.queue
      out:
        restaurantesOrquestrador: Restaurantes-Orquestrador.queue

server:
  port: 0

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator

# Eurika configuration
eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://service-registry:8762/eureka

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
