spring:
  application:
    name: restaurant-service
  mvc:
    problemdetails:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/tech-challenge
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        default-requeue-rejected: false

  datasource:
    url: jdbc:postgresql://restaurant-service-db:5432/restaurant-service-db
    username: postgres
    password: password
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true


app:
  rabbit:
    exchange: ex.main
    queues:
      in:
        orderPaidRestaurant: Order-Paid-Restaurant.queue

keycloak:
  admin:
    url: http://keycloak:8080
    realm: tech-challenge
    admin-username: admin
    admin-password: admin
    admin-client-id: admin-cli

server:
  port: 0
  error:
    include-stacktrace: never
    include-message: always

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator

# Eurika configuration
eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://service-registry:8762/eureka

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  level:
    br.com.fiap.restaurant: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{correlationId:-}] [%thread] %-5level %logger{36} - %msg%n"
